export default acoes =>{

    return  acoes =[
        { codigo: 'VALE3', nome: 'VALE' },
        { codigo: 'ITUB4', nome: 'ITAUUNIBANCO' },
        { codigo: 'B3SA3', nome: 'B3' },
        { codigo: 'PETR4', nome: 'PETROBRAS' },
        { codigo: 'BBDC4', nome: 'BRADESCO' },
        { codigo: 'PETR3', nome: 'PETROBRAS' },
        { codigo: 'ABEV3', nome: 'AMBEV S/A' },
        { codigo: 'BBAS3', nome: 'BRASIL' },
        { codigo: 'MGLU3', nome: 'MAGAZ LUIZA' },
        { codigo: 'ITSA4', nome: 'ITAUSA' },
        { codigo: 'WEGE3', nome: 'WEG' },
        { codigo: 'JBSS3', nome: 'JBS' },
        { codigo: 'LREN3', nome: 'LOJAS RENNER' },
        { codigo: 'GNDI3', nome: 'INTERMEDICA' },
        { codigo: 'NTCO3', nome: 'GRUPO NATURA' },
        { codigo: 'SUZB3', nome: 'SUZANO S.A.' },
        { codigo: 'RENT3', nome: 'LOCALIZA' },
        { codigo: 'BBDC3', nome: 'BRADESCO' },
        { codigo: 'EQTL3', nome: 'EQUATORIAL' },
        { codigo: 'RADL3', nome: 'RAIADROGASIL' },
        { codigo: 'RAIL3', nome: 'RUMO S.A.' },
        { codigo: 'VVAR3', nome: 'VIAVAREJO' },
        { codigo: 'LAME4', nome: 'LOJAS AMERIC' },
        { codigo: 'BTOW3', nome: 'B2W DIGITAL' },
        { codigo: 'UGPA3', nome: 'ULTRAPAR' },
        { codigo: 'VIVT4', nome: 'TELEF BRASIL' },
        { codigo: 'SBSP3', nome: 'SABESP' },
        { codigo: 'BBSE3', nome: 'BBSEGURIDADE' },
        { codigo: 'CCRO3', nome: 'CCR SA' },
        { codigo: 'BRFS3', nome: 'BRF SA' },
        { codigo: 'GGBR4', nome: 'GERDAU' },
        { codigo: 'BRDT3', nome: 'PETROBRAS BR' },
        { codigo: 'BPAC11', nome: 'BTGP BANCO' },
        { codigo: 'KLBN11', nome: 'KLABIN S/A' },
        { codigo: 'HAPV3', nome: 'HAPVIDA' },
        { codigo: 'HYPE3', nome: 'HYPERA' },
        { codigo: 'SULA11', nome: 'SUL AMERICA' },
        { codigo: 'COGN3', nome: 'COGNA ON' },
        { codigo: 'ENGI11', nome: 'ENERGISA' },
        { codigo: 'TIMP3', nome: 'TIM PART S/A' },
        { codigo: 'ELET3', nome: 'ELETROBRAS' },
        { codigo: 'CSAN3', nome: 'COSAN' },
        { codigo: 'PCAR3', nome: 'P.ACUCAR-CBD' },
        { codigo: 'EGIE3', nome: 'ENGIE BRASIL' },
        { codigo: 'CMIG4', nome: 'CEMIG' },
        { codigo: 'SANB11', nome: 'SANTANDER BR' },
        { codigo: 'YDUQ3', nome: 'YDUQS PART' },
        { codigo: 'TOTS3', nome: 'TOTVS' },
        { codigo: 'BRML3', nome: 'BR MALLS PAR' },
        { codigo: 'IRBR3', nome: 'IRBBRASIL RE' },
        { codigo: 'ELET6', nome: 'ELETROBRAS' },
        { codigo: 'QUAL3', nome: 'QUALICORP' },
        { codigo: 'BRAP4', nome: 'BRADESPAR' },
        { codigo: 'CRFB3', nome: 'CARREFOUR BR' },
        { codigo: 'FLRY3', nome: 'FLEURY' },
        { codigo: 'CSNA3', nome: 'SID NACIONAL' },
        { codigo: 'CYRE3', nome: 'CYRELA REALT' },
        { codigo: 'AZUL4', nome: 'AZUL' },
        { codigo: 'BRKM5', nome: 'BRASKEM' },
        { codigo: 'TAEE11', nome: 'TAESA' },
        { codigo: 'EMBR3', nome: 'EMBRAER' },
        { codigo: 'MULT3', nome: 'MULTIPLAN' },
        { codigo: 'MRVE3', nome: 'MRV' },
        { codigo: 'CIEL3', nome: 'CIELO' },
        { codigo: 'ENBR3', nome: 'ENERGIAS BR' },
        { codigo: 'CPFE3', nome: 'CPFL ENERGIA' },
        { codigo: 'MRFG3', nome: 'MARFRIG' },
        { codigo: 'GOAU4', nome: 'GERDAU MET' },
        { codigo: 'USIM5', nome: 'USIMINAS' },
        { codigo: 'BEEF3', nome: 'MINERVA' },
        { codigo: 'IGTA3', nome: 'IGUATEMI' },
        { codigo: 'CVCB3', nome: 'CVC BRASIL' },
        { codigo: 'GOLL4', nome: 'GOL' },
        { codigo: 'ECOR3', nome: 'ECORODOVIAS' },
        { codigo: 'HGTX3', nome: 'CIA HERING' },


    ]
}


